### ISSUE TITLE
Inspect, upload and download data to/from volumes

### ISSUE THREAD

**Issue by qiuwei** [EUDAT-GEF/GEF#12]
https://github.com/docker/docker/issues/18670

This links might be useful.
Anonymous volumes do copy data automatically, but it seems this api might be changed in the future.

There are two methods I come up with,
1. get the mountpoint of named volumes on the host system, gef-docker copies the data uploaded by the users to that path.
pros: easy to implement.
cons: requires root access(Any workaround?)
2. Run an ephemeral container, which mounts two volumes, i.e. the named volume and the volume binds t where the user uploads data, then do a copy.

**Comment by emanueldima** [comment]
1. Try getting a list of files from a volume bound to a container, using https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/inspect-changes-on-a-containers-filesystem
2. Try to upload/download files from a volume bound to a container using https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/get-an-archive-of-a-filesystem-resource-in-a-container

**Comment by emanueldima** [comment]
solved
