### ISSUE TITLE
Container that downloads files from a volume is not removed after its job is done

### ISSUE THREAD

**Issue by ubuntolog** [EUDAT-GEF/GEF#133]
After download is initiated the corresponding container/swarm service is not removed. But if we try to remove it, we see the error: "caused by: task: non-zero exit (1)"

See the code https://github.com/EUDAT-GEF/GEF/blob/master/gefserver/pier/staging.go#L29

**Comment by emanueldima** [comment]
What's the error?

**Comment by ubuntolog** [comment]
Sorry, it was my alternative branch. In the master branch the container is not removed. It remains on the machine after downloading a file

**Comment by emanueldima** [comment]
I see that in the `func (p *Pier) DownStreamContainerFile` we don't close the tar stream (`defer tarStream.Close()`) before end, so probably that's why we cannot remove the container safely after copying.

**Comment by ubuntolog** [comment]
tarStream does not have Close() method
