### ISSUE TITLE
Titles on jobs page only refer to 'Job from unknown service' under Mozilla Firefox

### ISSUE THREAD

**Issue by arajapak** [EUDAT-GEF/GEF#150]
The 'Title' row on the 'Jobs' page only reads 'Job from unknown service' when viewed with Mozilla Firefox under Debian Linux instead of referring to the actual service invoked. This issue occurs regardless of the user role of the profile used. All other rows are shown as expected. When browsing with Safari and Google Chrome under MacOS, the job titles are complete, e.g. 'Job from Stanford Parser for English' is shown as job title.

**Comment by ubuntolog** [comment]
I tried Firefox 55.0.2 and there were no problems with titles

**Comment by arajapak** [comment]
I tried that too and it worked as it should.

**Comment by ubuntolog** [comment]
I will try to open it from my laptop with Ubuntu

**Comment by ubuntolog** [comment]
Works on Debian 9 in Firefox 52.3.0 and Chrome

**Comment by ubuntolog** [comment]
No problems with Debian 8.9 Jassie and Firefox 52.3.0

**Comment by arajapak** [comment]
Then we simply need to recommend using a current version of Firefox as we cannot guarantee compatibility with older versions.
