### ISSUE TITLE
Users without privileges receive no warning when viewing the role managment page under Mozilla Firefox

### ISSUE THREAD

**Issue by arajapak** [EUDAT-GEF/GEF#152]
When viewing the 'Role Management' page as a logged in user without super admin privileges with Mozilla Firefox, no red warning can be seen indicating that the current role cannot add users to specific roles. When browsing with Safari and Google Chrome, the warnings are visible.

**Comment by ubuntolog** [comment]
This pull request https://github.com/EUDAT-GEF/GEF/pull/151 should fix the issue
