### ISSUE TITLE
Wrong filename while downloading from B2Drop

### ISSUE THREAD

**Issue by ubuntolog** [EUDAT-GEF/GEF#48]
Data staging container downloads a file from B2Drop and assigns "download" name to it. It causes problems for the service containers

**Comment by emanueldima** [comment]
Can you tell me what's the URL?

**Comment by ubuntolog** [comment]
https://b2drop.eudat.eu/s/ZQVUdhCB38q8aWo/download

**Comment by emanueldima** [comment]
fixed by https://github.com/EUDAT-GEF/GEF/pull/49
